system:
  debug: true
  device: cpu   # cpu / cuda

stitching:
  enable: true
  mode: panorama

detection:
  use_yolo: false
  yolo_model: weights/fusioncode_yolo.pt

decoding:
  enable_commercial_sdk: false
  retry_times: 3
